services:
  # Backend API service
  - type: web
    name: clinical-trial-search-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

  # Frontend service
  - type: web
    name: clinical-trial-search
    env: node
    plan: free
    buildCommand: cd client && npm install --legacy-peer-deps && npm run build
    startCommand: cd client && npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://clinical-trial-search-api.onrender.com
